name: Build and deploy to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Log into DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to DockerHub
        # Ideally we should be writing down steps like 
        # docker build -t <image-name> but all this logic has been abstracted
        # away by the use of pre-built actions :: docker/build-push-actions@v2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: riteshkoushik39/first-ci-cd-app:latest 

      - name: Verify Pushed Image
        run: docker pull riteshkoushik39/first-ci-cd-app
